INSERT INTO users (role, user_name, password, email, active, status) VALUES
('admin', 'admin1', 'password', 'admin1@example.com', true, 'completed'),
('admin', 'admin2', 'password', 'admin2@example.com', true, 'completed'),
('customer_support', 'support1', 'password', 'support1@example.com', true, 'completed'),
('customer_support', 'support2', 'password', 'support2@example.com', true, 'completed'),
('customer_support', 'support3', 'password', 'support3@example.com', true, 'completed'),
('customer_support', 'support4', 'password', 'support4@example.com', true, 'completed'),
('customer_support', 'support5', 'password', 'support5@example.com', true, 'pending'),
('customer_support', 'support6', 'password', 'support6@example.com', true, 'pending'),
('customer_support', 'support7', 'password', 'support7@example.com', false, 'completed'),
('customer_support', 'support8', 'password', 'support8@example.com', false, 'completed');

INSERT INTO cases (status, category, title, customer_first_name, customer_last_name, customer_email, case_opened, case_closed, case_handler) VALUES
('closed', 'shipping', 'Flight delayed by 12 hours, no compensation!', 'James', 'Anderson', 'james.anderson@example.com', '2025-02-21 08:47:51', '2025-02-22 08:47:51', 7),
('unopened', 'other', 'Unexpected baggage fee at check-in', 'Emma', 'Johnson', 'emma.johnson@example.com', NULL, NULL, 9),
('unopened', 'product', 'Seats changed without notice, very frustrating', 'Oliver', 'Brown', 'oliver.brown@example.com', NULL, NULL, 6),
('closed', 'other', 'Fantastic customer service at the airport!', 'Sophia', 'Martinez', 'sophia.martinez@example.com', '2025-02-17 08:47:51', '2025-02-22 08:47:51', 6),
('unopened', 'product', 'Missed connection due to airline''s mistake', 'Liam', 'Garcia', 'liam.garcia@example.com', NULL, NULL, 6),
('closed', 'other', 'Refund taking too long, need urgent help', 'Isabella', 'Smith', 'isabella.smith@example.com', '2025-03-05 08:47:51', '2025-03-09 08:47:51', 4),
('unopened', 'shipping', 'Loyalty points not credited after booking', 'Ethan', 'Hernandez', 'ethan.hernandez@example.com', NULL, NULL, 9),
('closed', 'shipping', 'Overbooked flight left me stranded!', 'Ava', 'Taylor', 'ava.taylor@example.com', '2025-03-13 08:47:51', '2025-03-17 08:47:51', 5),
('closed', 'payment', 'Train ticket cancelled but no refund issued', 'Lucas', 'White', 'lucas.white@example.com', '2025-03-06 08:47:51', '2025-03-09 08:47:51', 3),
('open', 'product', 'Super smooth check-in experience, thanks!', 'Mia', 'Moore', 'mia.moore@example.com', '2025-02-14 08:47:51', NULL, 6),
('unopened', 'other', 'Airline lost my baggage, no response!', 'Noah', 'Davis', 'noah.davis@example.com', NULL, NULL, 9),
('closed', 'product', 'Had to pay extra for seat selection, why?', 'Charlotte', 'Adams', 'charlotte.adams@example.com', '2025-02-28 08:47:51', '2025-03-01 08:47:51', 10),
('unopened', 'payment', 'Really polite and helpful ground staff', 'Benjamin', 'Walker', 'benjamin.walker@example.com', NULL, NULL, 10),
('unopened', 'shipping', 'Error in online booking system, charged twice', 'Amelia', 'Lee', 'amelia.lee@example.com', NULL, NULL, 6),
('open', 'product', 'Late-night flight rescheduled without notice', 'Elijah', 'Gonzalez', 'elijah.gonzalez@example.com', '2025-02-14 08:47:51', NULL, 5),
('unopened', 'payment', 'Best flight experience ever, great staff!', 'Harper', 'King', 'harper.king@example.com', NULL, NULL, 9),
('open', 'shipping', 'Compensation policy not clear, need clarification', 'Henry', 'Scott', 'henry.scott@example.com', '2025-03-07 08:47:51', NULL, 7),
('closed', 'product', 'Boarding gate changed last minute, very stressful', 'Evelyn', 'Green', 'evelyn.green@example.com', '2025-02-22 08:47:51', '2025-02-23 08:47:51', 6),
('open', 'shipping', 'Customer support was amazing, really helpful', 'Daniel', 'Baker', 'daniel.baker@example.com', '2025-03-03 08:47:51', NULL, 3),
('unopened', 'other', 'Horrible experience with online check-in system', 'Scarlett', 'Nelson', 'scarlett.nelson@example.com', NULL, NULL, 4);

INSERT INTO messages (case_id, message, timestamp, is_sender_customer) VALUES

(1, 'The delivery was supposed to arrive yesterday, but there''s no update. I need assistance resolving this issue as soon as possible.', '2025-02-23 03:46:51', true),
(1, 'The shipping delay is causing me problems. Please assist.', '2025-02-25 05:59:51', false),
(2, 'I have a general inquiry about my booking. I need assistance resolving this issue as soon as possible.', '2025-03-10 09:21:34', true),
(3, 'I got the wrong product. I need a replacement. I need assistance resolving this issue as soon as possible.', '2025-02-14 09:21:34', true),
(4, 'I was promised compensation, but I haven''t received it. I need assistance resolving this issue as soon as possible.', '2025-02-23 20:59:51', true),
(4, 'I need help with a special request for my booking.', '2025-02-25 05:49:51', false),
(5, 'The item I received is damaged. What are the next steps? I need assistance resolving this issue as soon as possible.', '2025-02-20 09:21:34', true),
(6, 'I have a general inquiry about my booking. I need assistance resolving this issue as soon as possible.', '2025-03-09 19:16:51', true),
(6, 'Your customer service was great! Thank you.', '2025-03-11 00:28:51', false),
(7, 'My package hasn''t arrived yet. The tracking information hasn''t updated in days. I need assistance resolving this issue as soon as possible.', '2025-02-24 09:21:34', true),
(8, 'The delivery was supposed to arrive yesterday, but there''s no update. I need assistance resolving this issue as soon as possible.', '2025-03-18 02:35:51', true),
(8, 'I need my order urgently. Can you provide an update?', '2025-03-20 02:31:51', false),
(9, 'I requested a refund, but I haven''t received it yet. I need assistance resolving this issue as soon as possible.', '2025-03-10 01:27:51', true),
(9, 'I tried making a payment, but it failed. What should I do?', '2025-03-11 00:57:51', false),
(10, 'The quality of the product is not as described. I need assistance resolving this issue as soon as possible.', '2025-02-15 13:00:51', true),
(10, 'The quality of the product is not as described.', '2025-02-16 08:34:51', false),
(11, 'I had a bad experience with my last trip. I need assistance resolving this issue as soon as possible.', '2025-03-06 09:21:34', true),
(12, 'The product stopped working after just a few days. I need assistance resolving this issue as soon as possible.', '2025-03-02 18:53:51', true),
(12, 'I ordered a different size. Can I exchange this?', '2025-03-03 06:04:51', false),
(13, 'There''s an unauthorized charge on my account. Please help. I need assistance resolving this issue as soon as possible.', '2025-03-10 09:21:34', true),
(14, 'I need my order urgently. Can you provide an update? I need assistance resolving this issue as soon as possible.', '2025-03-06 09:21:34', true),
(15, 'I ordered a different size. Can I exchange this? I need assistance resolving this issue as soon as possible.', '2025-02-15 17:15:51', true),
(15, 'I got the wrong product. I need a replacement.', '2025-02-16 07:00:51', false),
(15, 'The quality of the product is not as described. I need assistance resolving this issue as soon as possible.', '2025-02-16 14:59:51', true),
(15, 'The product stopped working after just a few days.', '2025-02-16 17:17:51', false),
(16, 'I requested a refund, but I haven''t received it yet. I need assistance resolving this issue as soon as possible.', '2025-02-25 09:21:34', true),
(17, 'My package hasn''t arrived yet. The tracking information hasn''t updated in days. I need assistance resolving this issue as soon as possible.', '2025-03-08 18:36:51', true),
(17, 'My package hasn''t arrived yet. The tracking information hasn''t updated in days.', '2025-03-09 04:01:51', false),
(17, 'The shipping delay is causing me problems. Please assist. I need assistance resolving this issue as soon as possible.', '2025-03-09 13:58:51', true),
(17, 'The shipping delay is causing me problems. Please assist.', '2025-03-09 16:24:51', false),
(17, 'I need my order urgently. Can you provide an update? I need assistance resolving this issue as soon as possible.', '2025-03-10 06:56:51', true),
(18, 'The item I received is damaged. What are the next steps? I need assistance resolving this issue as soon as possible.', '2025-02-24 01:49:51', true),
(18, 'I ordered a different size. Can I exchange this?', '2025-02-25 01:20:51', false),
(18, 'I ordered a different size. Can I exchange this? I need assistance resolving this issue as soon as possible.', '2025-02-25 06:37:51', true),
(18, 'I ordered a different size. Can I exchange this?', '2025-02-25 14:51:51', false),
(19, 'The estimated delivery date has passed. What''s the status? I need assistance resolving this issue as soon as possible.', '2025-03-04 09:10:51', true),
(19, 'My package hasn''t arrived yet. The tracking information hasn''t updated in days.', '2025-03-04 11:18:51', false),
(19, 'The shipping delay is causing me problems. Please assist. I need assistance resolving this issue as soon as possible.', '2025-03-04 17:17:51', true),
(19, 'The delivery was supposed to arrive yesterday, but there''s no update.', '2025-03-06 03:40:51', false),
(20, 'I have a general inquiry about my booking. I need assistance resolving this issue as soon as possible.', '2025-03-02 09:21:34', true);