# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI/CD Test

on:
  push:
    branches: ["main"]
  
jobs:
  
  gui_tests:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Test DB connection
        run: |
          echo "Checking DB connection..."
          pg_isready -h $DB_HOST -p $DB_PORT -U $DB_USER
        env:
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Install dotnet projec dependencies
        run: dotnet restore SecuremeTests/SecuremeTests.csproj

      - name: Build UI test project
        run: cd SecuremeTests && dotnet build 

      - name: Install Playwright Browsers
        run: cd SecuremeTests && pwsh bin/Debug/net9.0/playwright.ps1 install --with-deps

      - name: Start .NET backend
        run: |
          echo "Starting backend..."
          cd Secureme/server
          
          # Build first
          dotnet build
          
          # Run without the --no-build flag
          dotnet run &
          
          # Store the PID
          echo $! > ../backend.pid
          
          # Wait for the server to be ready with better logging
          for i in {1..30}; do
            if curl -s http://0.0.0.0:3000/api > /dev/null; then
              echo "Backend started successfully"
              break
            fi
            echo "Waiting for backend ($i/30)..."
            # Print dotnet process status
            ps aux | grep dotnet
            sleep 2
          done
          
          # Add error checking
          if ! ps -p $(cat ../backend.pid) > /dev/null; then
            echo "Backend process is not running!"
            echo "=== Build Output ==="
            cat bin/Debug/net9.0/*.log 2>/dev/null || echo "No build logs found"
            exit 1

      - name: Verify backend build
        run: |
          cd Secureme/server
          dotnet build --configuration Release
        
      - name: Check if anything is listening on port 3000
        run: |
          echo "Checking what is listening on port 3000..."
          sudo lsof -i :3000 || echo "Nothing is listening on port 3000"

      - name: Try to connect to the backend server
        run: |
          echo "Trying to curl http://0.0.0.0:3000..."
          curl -v --retry 5 --retry-delay 2 http://0.0.0.0:3000 || echo "curl failed to reach http://0.0.0.0:3000"

      - name: Display IP and port bindings
        run: |
          echo "IP and port bindings info:"
          ip addr
          netstat -tulpn 2>/dev/null || ss -tulpn

      - name: Run UI tests
        run: dotnet test SecuremeTests/SecuremeTests.csproj

