# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI/CD Test

on:
  push:
    branches: ["main"]
  
jobs:
  
  gui_tests:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Test DB connection
        run: |
          echo "Checking DB connection..."
          pg_isready -h $DB_HOST -p $DB_PORT -U $DB_USER
        env:
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}

      # Build server project first
      - name: Restore projects
        run: dotnet restore

      - name: Build projects
        run: dotnet build

      - name: Install Playwright Browsers
        run: cd SecuremeTests.csproj && pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps

      - name: Start server
        run: cd Secureme/server && nohup dotnet run &

      - name: Run UI tests
        run: cd securemetests && dotnet test 

