# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI/CD Test

on:
  push:
    branches: ["main"]

jobs:
  gui_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install dependencies
        run: dotnet restore SecuremeTests/SecuremeTests.csproj

      - name: Build UI test project
        run: dotnet build SecuremeTests/SecuremeTests.csproj

      - name: Install Playwright Browsers
        run: pwsh SecuremeTests/bin/Debug/net8.0/playwright.ps1 install --with-deps

      - name: Start backend
        run: nohup dotnet run --project Secureme/server &

      - name: Run UI tests
        run: dotnet test SecuremeTests/SecuremeTests.csproj
 
