# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI/CD Test

on:
  push:
    branches: ["main"]
  
jobs:
  
  gui_tests:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Test DB connection
        run: |
          echo "Checking DB connection..."
          pg_isready -h $DB_HOST -p $DB_PORT -U $DB_USER
        env:
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Install dotnet projec dependencies
        run: dotnet restore SecuremeTests/SecuremeTests.csproj

      - name: Build UI test project
        run: cd SecuremeTests && dotnet build 

      - name: Install Playwright Browsers
        run: cd SecuremeTests && pwsh bin/Debug/net9.0/playwright.ps1 install --with-deps

      - name: Start .NET backend
        run: |
          echo "Starting backend..."
          cd Secureme/server
          # Run with direct output instead of background
          dotnet run --project --no-build &
          
          # Store the PID
          echo $! > ../backend.pid
          
          # Wait for the server to be ready
          for i in {1..30}; do
            if curl -s http://0.0.0.0:3000/api > /dev/null; then
              echo "Backend started successfully"
              break
            fi
            echo "Waiting for backend ($i/30)..."
            sleep 2
          done
          
          # Debug information
          echo "=== Process Status ==="
          ps aux | grep dotnet
          
          echo "=== Network Status ==="
          netstat -tulpn || ss -tulpn
          
          # Verify the server is running
          if ! curl -v http://0.0.0.0:3000/api; then
            echo "=== Backend Log ==="
            cat backend.log || echo "No backend.log found"
            echo "=== Last 50 lines of system log ==="
            tail -n 50 /var/log/syslog || true
            exit 1

        
      - name: Check if anything is listening on port 3000
        run: |
          echo "Checking what is listening on port 3000..."
          sudo lsof -i :3000 || echo "Nothing is listening on port 3000"

      - name: Try to connect to the backend server
        run: |
          echo "Trying to curl http://0.0.0.0:3000..."
          curl -v --retry 5 --retry-delay 2 http://0.0.0.0:3000 || echo "curl failed to reach http://0.0.0.0:3000"

      - name: Display IP and port bindings
        run: |
          echo "IP and port bindings info:"
          ip addr
          netstat -tulpn 2>/dev/null || ss -tulpn

      - name: Run UI tests
        run: dotnet test SecuremeTests/SecuremeTests.csproj

