# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI/CD Test

on:
  push:
    branches: ["main"]

jobs:
  # Name of the job/test

  gui_tests:
    runs-on: ubuntu-latest
    # needs: api_tests # Kör endast om api testerna går igenom
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Install dotnet project dependencies
        run: dotnet restore
        
      - name: Build/Restore Playwright Project
        run: cd SecuremeTests && dotnet build
        
      - name: Ensure browsers are installed
        run: cd SecuremeTests && pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps
        
      - name: Start server
        run: cd Secrueme/server && nohup dotnet run &
        
      - name: Run GUI-tests
        run: cd SecuremeTests && dotnet test

 
