# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI/CD Test

#on:
  #push:
    #branches: ["main"]
  
jobs:
  
  gui_tests:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Test DB connection
        run: |
          echo "Checking DB connection..."
          pg_isready -h $DB_HOST -p $DB_PORT -U $DB_USER
        env:
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Install dependencies
        run: dotnet restore SecuremeTests/SecuremeTests.csproj

      - name: Install frontend dependencies
        run: |
          cd Secureme/client
          npm ci

      - name: Build UI test project
        run: dotnet build SecuremeTests/SecuremeTests.csproj

      - name: Install Playwright Browsers
        run: pwsh SecuremeTests/bin/Debug/net9.0/playwright.ps1 install --with-deps

      - name: Start backend
        run: nohup dotnet run --project Secureme/server &

      - name: Start frontend (Vite) dev server
        run: |
          cd Secureme/client
          nohup npm run dev -- --host &
          
      - name: Debug frontend
        run: curl http://localhost:5173
        
      - name: Wait for frontend to be ready
        run: npx wait-on http://localhost:5173

      - name: Run UI tests
        run: dotnet test SecuremeTests/SecuremeTests.csproj
 
